algo = input('Digite algo: ')

tipo_primitivo = type(algo)
print('O tipo primitivo desse valor é {}'.format(tipo_primitivo))
tem_espaco = algo.isspace()
print('So tem espaços? {}'.format(tem_espaco))
e_numero = algo.isnumeric()
print('É um número? {}'.format(e_numero))
e_alfabetico = algo.isalpha()
print('É alfabetico? {}'.format(e_alfabetico))
e_alfanumerico = algo.isalnum()
print('É alfanumerico? {}'.format(e_alfanumerico))
maiuscula = algo.isupper()
print('É maiuscula? {}'.format(maiuscula))
minuscula = algo.islower()
print('É minuscula? {}'.format(minuscula))
capitalizada = algo.istitle()
print('Esta capitalizada? {}'.format(capitalizada))

